/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tuJOKDmGNdk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

export function ChatUI() {
  return (
    (<div key="1" className="flex min-h-screen w-full flex-col bg-[#0c0f14]">
      <div
        className="flex flex-1 flex-col overflow-y-auto px-6 py-4 bg-[#0e1726]"
        style={{
          backgroundColor: "#0e1726",
          scrollbarColor: "#2c3546 #0e1726",
          scrollbarWidth: "thin",
        }}>
        <div className="flex flex-col gap-4 mx-auto max-w-3xl">
          <div className="flex justify-start">
            <div
              className="rounded-tl-lg rounded-tr-lg rounded-br-lg bg-transparent px-4 py-3 text-white shadow-md"
              id="server-output">
              <p className="typed-text font-serif">Hello, how can I assist you today?</p>
            </div>
          </div>
          <div className="flex justify-end ml-[20px]">
            <div
              className="rounded-tl-lg rounded-tr-lg rounded-br-lg bg-[#1e3a57] px-4 py-3 text-white shadow-md"
              id="user-input">
              <p className="font-sans">
                I'm looking to create a sophisticated chatbot interface for my personal portfolio website.
              </p>
            </div>
          </div>
          <div className="flex justify-start">
            <div
              className="rounded-tl-lg rounded-tr-lg rounded-br-lg bg-transparent px-4 py-3 text-white shadow-md"
              id="server-output">
              <p className="typed-text font-serif">
                Certainly, I can help you with that. What kind of design and features are you looking for?
              </p>
            </div>
          </div>
          <div className="flex justify-end ml-[20px]">
            <div
              className="rounded-tl-lg rounded-tr-lg rounded-br-lg bg-[#1e3a57] px-4 py-3 text-white shadow-md">
              <p className="font-sans">
                I'm looking for a sleek and modern design with a minimalist aesthetic. The chatbot should have a
                friendly and approachable personality, but also maintain a professional tone. Some key features I'd like
                are the ability to handle complex queries, provide relevant information and resources, and offer
                suggestions or recommendations based on the user's input.
              </p>
            </div>
          </div>
          <div className="flex justify-start">
            <div
              className="rounded-tl-lg rounded-tr-lg rounded-br-lg bg-transparent px-4 py-3 text-white shadow-md"
              id="server-output">
              <p className="typed-text font-serif">
                Understood. I can create a sophisticated and elegant chatbot interface that meets your requirements. Let
                me get started on the design right away.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        className="flex items-center justify-center px-4 py-2"
        style={{
          backgroundColor: "#0e1726",
        }}>
        <div
          className="flex w-full max-w-3xl rounded-full bg-[#1e2c3f] px-4 py-2 shadow-inner shadow-[#0c0f14]">
          <textarea
            className="flex-1 rounded-full bg-transparent px-4 py-2 text-white font-sans focus:outline-none focus:ring-2 focus:ring-[#071121] focus:ring-opacity-50 resize-none overflow-y-auto shadow-[0_0_10px_rgba(255,255,255,0.1)] focus:shadow-[0_0_20px_rgba(255,255,255,0.2)] transition-shadow"
            placeholder="Type your message..."
            rows={1} />
          <button
            className="ml-4 rounded-full bg-gradient-to-r from-[#1e2533] to-[#0f1a2b] px-4 py-2 text-white shadow-md transition-colors hover:bg-gradient-to-br hover:from-[#071121] hover:to-[#1e2533] focus:outline-none focus:ring-2 focus:ring-[#071121] focus:ring-opacity-50">
            <SendIcon
              className="h-4 w-4 transition-transform hover:scale-110 hover:brightness-125" />
          </button>
        </div>
      </div>
      <footer
        className="flex w-full items-center justify-center bg-[#0e1726] py-0.5 text-center text-xs text-white">
        <span className="font-sans text-[10px]">© Dhairya Gajjar 2024. All rights reserved.</span>
      </footer>
    </div>)
  );
}

function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}
